### ISSUE TITLE
Link dead?

### ISSUE THREAD

**Issue by lukeramsden** [parttimenerd/jfreventcollector#3]
Seems like https://sap.github.io/SapMachine/jfrevents/ is now a 404, as of writing - was deleted in this commit https://github.com/SAP/SapMachine/commit/00aeb9e3988836952ba27654ae4b5535982b9f4d

**Comment by parttimenerd** [comment]
Thanks for noticing this, I restarted the site generation.

**Comment by parttimenerd** [comment]
There is a NullPointerException in the site generator:

```java
Exception in thread "main" java.lang.NullPointerException
	at me.bechberger.collector.site.Main.formatExample(Main.kt:422)
	at me.bechberger.collector.site.Main.formatExample(Main.kt:445)
	at me.bechberger.collector.site.Main.formatExample(Main.kt:445)
	at me.bechberger.collector.site.Main.formatExample$default(Main.kt:408)
	at me.bechberger.collector.site.Main.createExampleScope(Main.kt:461)
	at me.bechberger.collector.site.Main.formatExamples(Main.kt:577)
	at me.bechberger.collector.site.Main.formatTypeExamples(Main.kt:589)
	at me.bechberger.collector.site.Main.createEventScope(Main.kt:623)
	at me.bechberger.collector.site.Main.formatEvent(Main.kt:628)
	at me.bechberger.collector.site.Main.createEventSection(Main.kt:641)
	at me.bechberger.collector.site.Main.body(Main.kt:668)
	at me.bechberger.collector.site.Main.createPage(Main.kt:172)
	at me.bechberger.collector.site.Main.create(Main.kt:179)
	at me.bechberger.collector.site.MainKt.main(Main.kt:710)
```

I'll fix this issue today(ish).

**Comment by lukeramsden** [comment]
No worries, good to know it's just a bug and not gone forever, it's very useful!

**Comment by parttimenerd** [comment]
I certainly plan to maintain it for a long time, as it's quite helpful when working with JFR.

**Comment by parttimenerd** [comment]
I fixed the issue and the site is up :)

P.S.: I'm open to contributions, so feel free to add new features via a PR.
